/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CharacterSchema extends BaseModel {
  static $columns = ['colors', 'createdAt', 'description', 'hardness', 'id', 'name', 'photoUrl', 'specie', 'updatedAt'] as const
  $columns = CharacterSchema.$columns
  @column()
  declare colors: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare hardness: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare photoUrl: string | null
  @column()
  declare specie: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
